node('master') {
    def commit_id
stage('prepration') {
checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/aerada/nitro2.git']]])
}
stage ('Docker build and push to dockerhub'){
    nodejs('nodejs') {
   sh 'npm -v'
    docker.withRegistry('https://index.docker.io/v1/', '8184c21d-5925-48b2-af7b-91544389c621') {
       def app = docker.build("karthi102/nitro2:${Build_Number}", '.').push()
	}
   
}
}
}
